// Auto-generated by generate-manifest.js — do not edit by hand.
window.BLOG_MANIFEST = [
  {
    "file": "31-07-2026-01.html",
    "date": "31 Jul 2026",
    "title": "Starting the lab notebook",
    "excerpt": "Why this log exists, and how the automated version of it works."
  }
];
